# https://github.com/elastic/kibana-docker
FROM registry.cn-hongkong.aliyuncs.com/my_007/kibana-oss:6.6.0
#FROM docker.elastic.co/kibana/kibana-oss:6.6.0

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
