# https://github.com/elastic/kibana-docker
FROM docker-hub.shiqutech.com:5000/oa/kibana-oss:7.4.2
#FROM docker.elastic.co/kibana/kibana-oss:6.6.0

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
