# https://github.com/elastic/logstash-docker
FROM docker-hub.shiqutech.com:5000/oa/logstash-oss:7.4.2
#FROM docker.elastic.co/logstash/logstash-oss:6.6.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
