# https://github.com/elastic/logstash-docker
FROM registry.cn-hongkong.aliyuncs.com/my_007/logstash-oss:6.6.0

#FROM docker.elastic.co/logstash/logstash-oss:6.6.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
