# https://github.com/elastic/elasticsearch-docker
FROM registry.cn-hongkong.aliyuncs.com/my_007/elasticsearch-oss:6.6.0
#FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
