# https://github.com/elastic/elasticsearch-docker
FROM docker-hub.shiqutech.com:5000/oa/elasticsearch-oss:7.4.2
#FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
