version: '2'
services:
    rundeck:
        image: 172.24.39.35:5000/oa/rundeck3.1
        restart: always
        networks:
         - default
        environment:
            RUNDECK_DATABASE_DRIVER: com.mysql.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: test
            RUNDECK_DATABASE_PASSWORD: ceshi
            RUNDECK_DATABASE_URL: jdbc:mysql://192.168.0.231/rundeck?autoReconnect=true&useSSL=false
            RUNDECK_GRAILS_URL: http://192.168.8.20:4440
        ports:
          - 4440:4440
        volumes:
          - /home/docker_mount/rundeck_data:/home/rundeck/server/data
        external_links:
          - centosphp56_centos_1 
        tty: true
        extra_hosts:
          - centosphp56_centos_1:172.19.0.3
