version: '2'
services:
    rundeck:
        image: docker-hub.shiqutech.com:5000/oa/rundeck:3.1.2
        restart: always
        environment:
            RUNDECK_DATABASE_DRIVER: com.mysql.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: test
            RUNDECK_DATABASE_PASSWORD: ceshi
            RUNDECK_DATABASE_URL: jdbc:mysql://192.168.8.33/rundeck?autoReconnect=true&useSSL=false
            RUNDECK_GRAILS_URL: http://192.168.8.35:4440
        ports:
          - 4440:4440
        volumes:
          - /home/docker_mount/rundeck_data:/home/rundeck/server/data
          - /home/docker_mount/rundeck_ssh/.ssh:/home/rundeck/.ssh
        external_links:
          - centosphp56_centos_1 
        tty: true

networks:
  default:
    external:
      name: centos-php56_it_network
